name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.psha }}
        

      - name: Cache Build Caches
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-check-build-cache-${{ steps.current-time.outputs.time }}
          path: |
            ~/Library/Developer/Xcode/DerivedData
          restore-keys: |
            ${{ runner.os }}-check-build-cache-
      

      - name: Build
        run: |
          xcodebuild -scheme 'Linecom Wear Translate Watch App' -configuration Release build CODE_SIGN_IDENTITY="" -quiet
